---
# Section 0: Simple user add depending on the OS distribution
- hosts: rhel
  gather_facts: true
  vars:
    userlist:
    - user1
    - user2
  tasks:
    - name: Create users
      block:
# Section 1: Check if users already exist in the servers. If they are nto on the servers procced to section 2      
        - getent:
            database: passwd 
            key: "{{ item }}"
            fail_key: yes
          loop: "{{ userlist }}"
# Notify that users already exist and continue directly to section 3
        - debug:
            msg: "User {{ item }} already exist on {{ ansible_hostname }}"
          loop: "{{ userlist }}"
# Section 2: Create the users in case of section 1 failure             
      rescue:
        - user:
            name:  "{{ item }}"
            state: present
          loop: "{{ userlist }}"
# OS condition            
          when: ansible_facts['os_family'] == "RedHat"
        - debug:
            msg: "User {{ item }} created on {{ ansible_hostname }}"
          loop: "{{ userlist }}"
# Section 3: Notify the end of playbook
      always:
        - debug:
            msg: "Playbook is finished!"
          
      