---
- name: Install packages
  hosts: rhel
  vars:
    webpackages:
     - httpd
     - php
     - postgresql
  tasks:
    - name: install web packages
      yum:
        name: "{{ item }}"
        state: present
      loop: "{{ webpackages }}"
      when: ansible_distribution == "RedHat" and  ansible_memtotal_mb > 152

    - name: start and enable web service
      block:
        - name: start and enable web service only
          service:
             name: "{{ item }}"
             state: started
             enabled: yes
          loop: "{{ webpackages }}"
          when: ansible_distribution == "RedHat" and ansible_memtotal_mb > 152

      rescue:
        - name: debug configuration error
          debug:
              msg: "one of the services can't be started and enabled"

    - name: edit httpd configuration file
      replace:
        path: /etc/httpd/conf/httpd.conf
        regexp: 'EnableSendfile on'
        replace: 'EnableSendfile off'
        backup: yes
      notify: restart httpd

    - name: Add services to firewall
      firewalld:
        service: "{{ item }}"
        permanent: true
        immediate: true
        state: enabled
      loop:
        - https
        - http

  handlers:
    - name: restart httpd
      service:
        name: httpd
        state: started