---
# Simple user add depending on the hostname
- hosts: all  
  tasks:
    - name: create users
      block:
        - name: Create multiple users
          user:
            name: "{{ item }}"
            state: present
            groups: wheel
          loop:
            - van
            - dal
      when: ansible_hostname == "gentoo"
      rescue:
        - debug: 
            msg: "Username already exists! "
      always:
        - debug:
            msg: " Users created succefully! "
        


