---
# Simple user add depending on the hostname
- hosts: rhel 
  tasks:
    - name: create users
      block:
        - user:
            name: "{{ item }}"
            state: present
            groups: wheel
            loop:
              - van
              - dal
          when: ansible_hostname == "gentoo"
      rescue:
        - debug: 
            msg: "Username already exists! "
      always:
        - debug:
            msg: " Users created succefully! "
        


