---
# Apt update & upgrade process
- name: Apt update 
  become: yes
  become_user: root
  tasks:
    - name: Updating system 
      ansible.builtin.apt:
        update_cache=yes force_apt_get=yes
    - name: Upgrading system
      apt: upgrade=yes force_apt_get=yes
      register: output
    - debug:
        var: "output.stdout_lines"


