---
- name: Fact dump
  hosts: localhost
  gather_facts: yes # not required. A toggle that controls if the fact modules are executed in parallel or serially and in order. This can guarantee the merge order of module facts at the expense of performance. By default it will be true if more than one fact module is used.
  tasks:
    - name: Print all facts
      debug:
        var: ansible_facts