---
# Install or remove service using tags
- name: Install or Remove services
  hosts: servera
  gather_facts: true
  vars:
    service:
      - httpd
      - git
      - wget
  tasks:
    - name: Install service
      dnf:
        name: "{{ item }}"
        state: present
      loop: "{{ service }}"
      tags: 
      - install # use install tag to install services
    - name: Delete services
      dnf:
        name: "{{ item }}"
        state: absent
      loop: "{{ service }}"
      tags:
      - delete # use delete tag to delete service

