---
# Copy file/directory between two remote hosts
- name: Sync files/directories from servera to serverb
  hosts: serverb # target host
  become: yes
  become_user: root
  tasks:
    - name: sync from servera to serverb
      synchronize:
        src: /tmp/file
        dest: /tmp/
      delegate_to: servera
