---
# tasks file for apache
- name: create website directory
  file:
    path: "{{ apache_web_dir }}"
    state: directory
    mode: '0755'
- name: add proper secontext on website directory
  sefcontext:
    target: '{{ apache_web_dir }}(/.*)?'
    setype: httpd_sys_content_t
    state: present
- name: install apache
  yum:
    name: httpd
    state: latest
- name: deploy httpd.conf template
  template:
    src: httpd.conf.j2
    dest: /etc/httpd/conf/httpd.conf
    backup: yes
  notify: "Restarting apache"
- name: deploy index.html template
  template:
    src: index.html.j2
    dest: "{{ apache_web_dir }}/index.html"
    backup: yes
- name: enable and start apache service
  service:
    name: httpd
    enabled: yes
    state: started


