---
- name: Quick install and test smoke apache 
  gather_facts: yes
  hosts: localhost
  become: yes
  become_user: root
  become_method: yes 
  tasks:
    - name: Install apache
      apt:
        name: apache2 
        update_cache: yes 
        state: latest
      when: ansible_facts['os_family'] == 'Debian'
    - name: start and enable service
      service:
        name: apache2 
        state: started
        enabled: yes
      when: ansible_facts['os_family'] == 'Debian'
    - name: Install apache
      dnf:
        name: httpd   
        state: latest
      when: ansible_facts['os_family'] == 'RedHat'
    - name: start and enable service
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_facts['os_family'] == 'RedHat'
    - name: Install apache
      pacman:
        name: apache  
        state: latest
      when: ansible_facts['os_family'] == 'Archlinux'
    - name: create index.html
      lineinfile:
        dest: /var/www/html/index.html
        state: present
        create: yes
        line: '{{ item }}' 
        owner: apache
        group: apache
        mode: 0644
      loop:
        - "<p>"
        - "Apache is running"
        - "</p>"
        - "<p>"
        - "on {{ ansible_distribution }} "
        - "<p>"
      notify: 
        - restart_apache
        - restart_httpd 
    - name: check for proper response  
      uri:    
        url: http://{{ansible_ssh_host}} 
        return_content: yes  
      register: result  
      until: '"Apache is running" in result.content' 
      retries: 5  
      delay: 1
  handlers:
    - name: restart_apache
      service:
            name: apache2
            state: restarted
    - name: restart_httpd
      service:
            name: httpd 
            state: restarted